version: '2'

services:
  frontend:
    container_name: reactapp
    build: 
      context: ./frontend/ 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: expressapp
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://davidan7845:docdann2899@cluster0.1ek00zj.mongodb.net/lawatty?retryWrites=true&w=majority
      - JWT_SECRET=palabrasupersecretajeje
