name: Build and Test

on:
  push:
    branches:
      - HU-22
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies in frontend
        working-directory: ./frontend
        run: yarn
      - name: Install dependencies in root
        working-directory: ./
        run: yarn
      - name: Test and Coverage
        working-directory: ./frontend
        run: yarn jest --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with: 
          projectBaseDir: frontend
          args: >
            -Dsonar.organization=desarrollo-lawatty
            -Dsonar.projectKey=David-A-Moreno_desarrollo-lawatty
            -Dsonar.sources=./frontend/src
            -Dsonar.test.exclusions=./frontend/src/app/page.jsx
            -Dsonar.tests=./frontend/__tests__
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
